version: '2.1'

services:
  neo4j:
    image: neo4j:5.7.0
    ports:
      - "7474:7474"
      - "7687:7687"
    mem_limit: 2048mb
    environment:
      - NEO4J_dbms_security_auth__enabled=false
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_dbms_security_procedures_allowlist=apoc.*,alg.classifiers.*
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,alg.classifiers.*
    volumes:
      - ./import:/var/lib/neo4j/import
      - ./plugins:/plugins